# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_EsunnyApi')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_EsunnyApi')
    _EsunnyApi = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_EsunnyApi', [dirname(__file__)])
        except ImportError:
            import _EsunnyApi
            return _EsunnyApi
        try:
            _mod = imp.load_module('_EsunnyApi', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _EsunnyApi = swig_import_helper()
    del swig_import_helper
else:
    import _EsunnyApi
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

try:
    import weakref
    weakref_proxy = weakref.proxy
except __builtin__.Exception:
    weakref_proxy = lambda x: x


class TapAPIApplicationInfo(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TapAPIApplicationInfo, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TapAPIApplicationInfo, name)
    __repr__ = _swig_repr
    __swig_setmethods__["AuthCode"] = _EsunnyApi.TapAPIApplicationInfo_AuthCode_set
    __swig_getmethods__["AuthCode"] = _EsunnyApi.TapAPIApplicationInfo_AuthCode_get
    if _newclass:
        AuthCode = _swig_property(_EsunnyApi.TapAPIApplicationInfo_AuthCode_get, _EsunnyApi.TapAPIApplicationInfo_AuthCode_set)
    __swig_setmethods__["KeyOperationLogPath"] = _EsunnyApi.TapAPIApplicationInfo_KeyOperationLogPath_set
    __swig_getmethods__["KeyOperationLogPath"] = _EsunnyApi.TapAPIApplicationInfo_KeyOperationLogPath_get
    if _newclass:
        KeyOperationLogPath = _swig_property(_EsunnyApi.TapAPIApplicationInfo_KeyOperationLogPath_get, _EsunnyApi.TapAPIApplicationInfo_KeyOperationLogPath_set)

    def __init__(self):
        this = _EsunnyApi.new_TapAPIApplicationInfo()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _EsunnyApi.delete_TapAPIApplicationInfo
    __del__ = lambda self: None
TapAPIApplicationInfo_swigregister = _EsunnyApi.TapAPIApplicationInfo_swigregister
TapAPIApplicationInfo_swigregister(TapAPIApplicationInfo)
cvar = _EsunnyApi.cvar
APIYNFLAG_YES = cvar.APIYNFLAG_YES
APIYNFLAG_NO = cvar.APIYNFLAG_NO
APILOGLEVEL_NONE = cvar.APILOGLEVEL_NONE
APILOGLEVEL_ERROR = cvar.APILOGLEVEL_ERROR
APILOGLEVEL_WARNING = cvar.APILOGLEVEL_WARNING
APILOGLEVEL_DEBUG = cvar.APILOGLEVEL_DEBUG
TAPI_COMMODITY_TYPE_NONE = cvar.TAPI_COMMODITY_TYPE_NONE
TAPI_COMMODITY_TYPE_SPOT = cvar.TAPI_COMMODITY_TYPE_SPOT
TAPI_COMMODITY_TYPE_FUTURES = cvar.TAPI_COMMODITY_TYPE_FUTURES
TAPI_COMMODITY_TYPE_OPTION = cvar.TAPI_COMMODITY_TYPE_OPTION
TAPI_COMMODITY_TYPE_SPREAD_MONTH = cvar.TAPI_COMMODITY_TYPE_SPREAD_MONTH
TAPI_COMMODITY_TYPE_SPREAD_COMMODITY = cvar.TAPI_COMMODITY_TYPE_SPREAD_COMMODITY
TAPI_COMMODITY_TYPE_BUL = cvar.TAPI_COMMODITY_TYPE_BUL
TAPI_COMMODITY_TYPE_BER = cvar.TAPI_COMMODITY_TYPE_BER
TAPI_COMMODITY_TYPE_STD = cvar.TAPI_COMMODITY_TYPE_STD
TAPI_COMMODITY_TYPE_STG = cvar.TAPI_COMMODITY_TYPE_STG
TAPI_COMMODITY_TYPE_PRT = cvar.TAPI_COMMODITY_TYPE_PRT
TAPI_COMMODITY_TYPE_BLT = cvar.TAPI_COMMODITY_TYPE_BLT
TAPI_COMMODITY_TYPE_BRT = cvar.TAPI_COMMODITY_TYPE_BRT
TAPI_COMMODITY_TYPE_DIRECTFOREX = cvar.TAPI_COMMODITY_TYPE_DIRECTFOREX
TAPI_COMMODITY_TYPE_INDIRECTFOREX = cvar.TAPI_COMMODITY_TYPE_INDIRECTFOREX
TAPI_COMMODITY_TYPE_CROSSFOREX = cvar.TAPI_COMMODITY_TYPE_CROSSFOREX
TAPI_COMMODITY_TYPE_INDEX = cvar.TAPI_COMMODITY_TYPE_INDEX
TAPI_COMMODITY_TYPE_STOCK = cvar.TAPI_COMMODITY_TYPE_STOCK
TAPI_COMMODITY_TYPE_SPOT_TRADINGDEFER = cvar.TAPI_COMMODITY_TYPE_SPOT_TRADINGDEFER
TAPI_COMMODITY_TYPE_FUTURE_LOCK = cvar.TAPI_COMMODITY_TYPE_FUTURE_LOCK
TAPI_COMMODITY_TYPE_EFP = cvar.TAPI_COMMODITY_TYPE_EFP
TAPI_COMMODITY_TYPE_TAS = cvar.TAPI_COMMODITY_TYPE_TAS
TAPI_CALLPUT_FLAG_CALL = cvar.TAPI_CALLPUT_FLAG_CALL
TAPI_CALLPUT_FLAG_PUT = cvar.TAPI_CALLPUT_FLAG_PUT
TAPI_CALLPUT_FLAG_NONE = cvar.TAPI_CALLPUT_FLAG_NONE
TAPI_AUTHTYPE_DIRECT = cvar.TAPI_AUTHTYPE_DIRECT
TAPI_AUTHTYPE_RELAY = cvar.TAPI_AUTHTYPE_RELAY

class TapAPICommodity(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TapAPICommodity, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TapAPICommodity, name)
    __repr__ = _swig_repr
    __swig_setmethods__["ExchangeNo"] = _EsunnyApi.TapAPICommodity_ExchangeNo_set
    __swig_getmethods__["ExchangeNo"] = _EsunnyApi.TapAPICommodity_ExchangeNo_get
    if _newclass:
        ExchangeNo = _swig_property(_EsunnyApi.TapAPICommodity_ExchangeNo_get, _EsunnyApi.TapAPICommodity_ExchangeNo_set)
    __swig_setmethods__["CommodityType"] = _EsunnyApi.TapAPICommodity_CommodityType_set
    __swig_getmethods__["CommodityType"] = _EsunnyApi.TapAPICommodity_CommodityType_get
    if _newclass:
        CommodityType = _swig_property(_EsunnyApi.TapAPICommodity_CommodityType_get, _EsunnyApi.TapAPICommodity_CommodityType_set)
    __swig_setmethods__["CommodityNo"] = _EsunnyApi.TapAPICommodity_CommodityNo_set
    __swig_getmethods__["CommodityNo"] = _EsunnyApi.TapAPICommodity_CommodityNo_get
    if _newclass:
        CommodityNo = _swig_property(_EsunnyApi.TapAPICommodity_CommodityNo_get, _EsunnyApi.TapAPICommodity_CommodityNo_set)

    def __init__(self):
        this = _EsunnyApi.new_TapAPICommodity()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _EsunnyApi.delete_TapAPICommodity
    __del__ = lambda self: None
TapAPICommodity_swigregister = _EsunnyApi.TapAPICommodity_swigregister
TapAPICommodity_swigregister(TapAPICommodity)

class TapAPIContract(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TapAPIContract, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TapAPIContract, name)
    __repr__ = _swig_repr
    __swig_setmethods__["Commodity"] = _EsunnyApi.TapAPIContract_Commodity_set
    __swig_getmethods__["Commodity"] = _EsunnyApi.TapAPIContract_Commodity_get
    if _newclass:
        Commodity = _swig_property(_EsunnyApi.TapAPIContract_Commodity_get, _EsunnyApi.TapAPIContract_Commodity_set)
    __swig_setmethods__["ContractNo1"] = _EsunnyApi.TapAPIContract_ContractNo1_set
    __swig_getmethods__["ContractNo1"] = _EsunnyApi.TapAPIContract_ContractNo1_get
    if _newclass:
        ContractNo1 = _swig_property(_EsunnyApi.TapAPIContract_ContractNo1_get, _EsunnyApi.TapAPIContract_ContractNo1_set)
    __swig_setmethods__["StrikePrice1"] = _EsunnyApi.TapAPIContract_StrikePrice1_set
    __swig_getmethods__["StrikePrice1"] = _EsunnyApi.TapAPIContract_StrikePrice1_get
    if _newclass:
        StrikePrice1 = _swig_property(_EsunnyApi.TapAPIContract_StrikePrice1_get, _EsunnyApi.TapAPIContract_StrikePrice1_set)
    __swig_setmethods__["CallOrPutFlag1"] = _EsunnyApi.TapAPIContract_CallOrPutFlag1_set
    __swig_getmethods__["CallOrPutFlag1"] = _EsunnyApi.TapAPIContract_CallOrPutFlag1_get
    if _newclass:
        CallOrPutFlag1 = _swig_property(_EsunnyApi.TapAPIContract_CallOrPutFlag1_get, _EsunnyApi.TapAPIContract_CallOrPutFlag1_set)
    __swig_setmethods__["ContractNo2"] = _EsunnyApi.TapAPIContract_ContractNo2_set
    __swig_getmethods__["ContractNo2"] = _EsunnyApi.TapAPIContract_ContractNo2_get
    if _newclass:
        ContractNo2 = _swig_property(_EsunnyApi.TapAPIContract_ContractNo2_get, _EsunnyApi.TapAPIContract_ContractNo2_set)
    __swig_setmethods__["StrikePrice2"] = _EsunnyApi.TapAPIContract_StrikePrice2_set
    __swig_getmethods__["StrikePrice2"] = _EsunnyApi.TapAPIContract_StrikePrice2_get
    if _newclass:
        StrikePrice2 = _swig_property(_EsunnyApi.TapAPIContract_StrikePrice2_get, _EsunnyApi.TapAPIContract_StrikePrice2_set)
    __swig_setmethods__["CallOrPutFlag2"] = _EsunnyApi.TapAPIContract_CallOrPutFlag2_set
    __swig_getmethods__["CallOrPutFlag2"] = _EsunnyApi.TapAPIContract_CallOrPutFlag2_get
    if _newclass:
        CallOrPutFlag2 = _swig_property(_EsunnyApi.TapAPIContract_CallOrPutFlag2_get, _EsunnyApi.TapAPIContract_CallOrPutFlag2_set)

    def __init__(self):
        this = _EsunnyApi.new_TapAPIContract()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _EsunnyApi.delete_TapAPIContract
    __del__ = lambda self: None
TapAPIContract_swigregister = _EsunnyApi.TapAPIContract_swigregister
TapAPIContract_swigregister(TapAPIContract)

class TapAPIExchangeInfo(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TapAPIExchangeInfo, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TapAPIExchangeInfo, name)
    __repr__ = _swig_repr
    __swig_setmethods__["ExchangeNo"] = _EsunnyApi.TapAPIExchangeInfo_ExchangeNo_set
    __swig_getmethods__["ExchangeNo"] = _EsunnyApi.TapAPIExchangeInfo_ExchangeNo_get
    if _newclass:
        ExchangeNo = _swig_property(_EsunnyApi.TapAPIExchangeInfo_ExchangeNo_get, _EsunnyApi.TapAPIExchangeInfo_ExchangeNo_set)
    __swig_setmethods__["ExchangeName"] = _EsunnyApi.TapAPIExchangeInfo_ExchangeName_set
    __swig_getmethods__["ExchangeName"] = _EsunnyApi.TapAPIExchangeInfo_ExchangeName_get
    if _newclass:
        ExchangeName = _swig_property(_EsunnyApi.TapAPIExchangeInfo_ExchangeName_get, _EsunnyApi.TapAPIExchangeInfo_ExchangeName_set)

    def __init__(self):
        this = _EsunnyApi.new_TapAPIExchangeInfo()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _EsunnyApi.delete_TapAPIExchangeInfo
    __del__ = lambda self: None
TapAPIExchangeInfo_swigregister = _EsunnyApi.TapAPIExchangeInfo_swigregister
TapAPIExchangeInfo_swigregister(TapAPIExchangeInfo)

class TapAPIChangePasswordReq(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TapAPIChangePasswordReq, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TapAPIChangePasswordReq, name)
    __repr__ = _swig_repr
    __swig_setmethods__["OldPassword"] = _EsunnyApi.TapAPIChangePasswordReq_OldPassword_set
    __swig_getmethods__["OldPassword"] = _EsunnyApi.TapAPIChangePasswordReq_OldPassword_get
    if _newclass:
        OldPassword = _swig_property(_EsunnyApi.TapAPIChangePasswordReq_OldPassword_get, _EsunnyApi.TapAPIChangePasswordReq_OldPassword_set)
    __swig_setmethods__["NewPassword"] = _EsunnyApi.TapAPIChangePasswordReq_NewPassword_set
    __swig_getmethods__["NewPassword"] = _EsunnyApi.TapAPIChangePasswordReq_NewPassword_get
    if _newclass:
        NewPassword = _swig_property(_EsunnyApi.TapAPIChangePasswordReq_NewPassword_get, _EsunnyApi.TapAPIChangePasswordReq_NewPassword_set)

    def __init__(self):
        this = _EsunnyApi.new_TapAPIChangePasswordReq()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _EsunnyApi.delete_TapAPIChangePasswordReq
    __del__ = lambda self: None
TapAPIChangePasswordReq_swigregister = _EsunnyApi.TapAPIChangePasswordReq_swigregister
TapAPIChangePasswordReq_swigregister(TapAPIChangePasswordReq)

class TapAPIQuoteLoginAuth(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TapAPIQuoteLoginAuth, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TapAPIQuoteLoginAuth, name)
    __repr__ = _swig_repr
    __swig_setmethods__["UserNo"] = _EsunnyApi.TapAPIQuoteLoginAuth_UserNo_set
    __swig_getmethods__["UserNo"] = _EsunnyApi.TapAPIQuoteLoginAuth_UserNo_get
    if _newclass:
        UserNo = _swig_property(_EsunnyApi.TapAPIQuoteLoginAuth_UserNo_get, _EsunnyApi.TapAPIQuoteLoginAuth_UserNo_set)
    __swig_setmethods__["ISModifyPassword"] = _EsunnyApi.TapAPIQuoteLoginAuth_ISModifyPassword_set
    __swig_getmethods__["ISModifyPassword"] = _EsunnyApi.TapAPIQuoteLoginAuth_ISModifyPassword_get
    if _newclass:
        ISModifyPassword = _swig_property(_EsunnyApi.TapAPIQuoteLoginAuth_ISModifyPassword_get, _EsunnyApi.TapAPIQuoteLoginAuth_ISModifyPassword_set)
    __swig_setmethods__["Password"] = _EsunnyApi.TapAPIQuoteLoginAuth_Password_set
    __swig_getmethods__["Password"] = _EsunnyApi.TapAPIQuoteLoginAuth_Password_get
    if _newclass:
        Password = _swig_property(_EsunnyApi.TapAPIQuoteLoginAuth_Password_get, _EsunnyApi.TapAPIQuoteLoginAuth_Password_set)
    __swig_setmethods__["NewPassword"] = _EsunnyApi.TapAPIQuoteLoginAuth_NewPassword_set
    __swig_getmethods__["NewPassword"] = _EsunnyApi.TapAPIQuoteLoginAuth_NewPassword_get
    if _newclass:
        NewPassword = _swig_property(_EsunnyApi.TapAPIQuoteLoginAuth_NewPassword_get, _EsunnyApi.TapAPIQuoteLoginAuth_NewPassword_set)
    __swig_setmethods__["QuoteTempPassword"] = _EsunnyApi.TapAPIQuoteLoginAuth_QuoteTempPassword_set
    __swig_getmethods__["QuoteTempPassword"] = _EsunnyApi.TapAPIQuoteLoginAuth_QuoteTempPassword_get
    if _newclass:
        QuoteTempPassword = _swig_property(_EsunnyApi.TapAPIQuoteLoginAuth_QuoteTempPassword_get, _EsunnyApi.TapAPIQuoteLoginAuth_QuoteTempPassword_set)
    __swig_setmethods__["ISDDA"] = _EsunnyApi.TapAPIQuoteLoginAuth_ISDDA_set
    __swig_getmethods__["ISDDA"] = _EsunnyApi.TapAPIQuoteLoginAuth_ISDDA_get
    if _newclass:
        ISDDA = _swig_property(_EsunnyApi.TapAPIQuoteLoginAuth_ISDDA_get, _EsunnyApi.TapAPIQuoteLoginAuth_ISDDA_set)
    __swig_setmethods__["DDASerialNo"] = _EsunnyApi.TapAPIQuoteLoginAuth_DDASerialNo_set
    __swig_getmethods__["DDASerialNo"] = _EsunnyApi.TapAPIQuoteLoginAuth_DDASerialNo_get
    if _newclass:
        DDASerialNo = _swig_property(_EsunnyApi.TapAPIQuoteLoginAuth_DDASerialNo_get, _EsunnyApi.TapAPIQuoteLoginAuth_DDASerialNo_set)

    def __init__(self):
        this = _EsunnyApi.new_TapAPIQuoteLoginAuth()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _EsunnyApi.delete_TapAPIQuoteLoginAuth
    __del__ = lambda self: None
TapAPIQuoteLoginAuth_swigregister = _EsunnyApi.TapAPIQuoteLoginAuth_swigregister
TapAPIQuoteLoginAuth_swigregister(TapAPIQuoteLoginAuth)

class TapAPIQuotLoginRspInfo(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TapAPIQuotLoginRspInfo, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TapAPIQuotLoginRspInfo, name)
    __repr__ = _swig_repr
    __swig_setmethods__["UserNo"] = _EsunnyApi.TapAPIQuotLoginRspInfo_UserNo_set
    __swig_getmethods__["UserNo"] = _EsunnyApi.TapAPIQuotLoginRspInfo_UserNo_get
    if _newclass:
        UserNo = _swig_property(_EsunnyApi.TapAPIQuotLoginRspInfo_UserNo_get, _EsunnyApi.TapAPIQuotLoginRspInfo_UserNo_set)
    __swig_setmethods__["UserType"] = _EsunnyApi.TapAPIQuotLoginRspInfo_UserType_set
    __swig_getmethods__["UserType"] = _EsunnyApi.TapAPIQuotLoginRspInfo_UserType_get
    if _newclass:
        UserType = _swig_property(_EsunnyApi.TapAPIQuotLoginRspInfo_UserType_get, _EsunnyApi.TapAPIQuotLoginRspInfo_UserType_set)
    __swig_setmethods__["UserName"] = _EsunnyApi.TapAPIQuotLoginRspInfo_UserName_set
    __swig_getmethods__["UserName"] = _EsunnyApi.TapAPIQuotLoginRspInfo_UserName_get
    if _newclass:
        UserName = _swig_property(_EsunnyApi.TapAPIQuotLoginRspInfo_UserName_get, _EsunnyApi.TapAPIQuotLoginRspInfo_UserName_set)
    __swig_setmethods__["QuoteTempPassword"] = _EsunnyApi.TapAPIQuotLoginRspInfo_QuoteTempPassword_set
    __swig_getmethods__["QuoteTempPassword"] = _EsunnyApi.TapAPIQuotLoginRspInfo_QuoteTempPassword_get
    if _newclass:
        QuoteTempPassword = _swig_property(_EsunnyApi.TapAPIQuotLoginRspInfo_QuoteTempPassword_get, _EsunnyApi.TapAPIQuotLoginRspInfo_QuoteTempPassword_set)
    __swig_setmethods__["ReservedInfo"] = _EsunnyApi.TapAPIQuotLoginRspInfo_ReservedInfo_set
    __swig_getmethods__["ReservedInfo"] = _EsunnyApi.TapAPIQuotLoginRspInfo_ReservedInfo_get
    if _newclass:
        ReservedInfo = _swig_property(_EsunnyApi.TapAPIQuotLoginRspInfo_ReservedInfo_get, _EsunnyApi.TapAPIQuotLoginRspInfo_ReservedInfo_set)
    __swig_setmethods__["LastLoginIP"] = _EsunnyApi.TapAPIQuotLoginRspInfo_LastLoginIP_set
    __swig_getmethods__["LastLoginIP"] = _EsunnyApi.TapAPIQuotLoginRspInfo_LastLoginIP_get
    if _newclass:
        LastLoginIP = _swig_property(_EsunnyApi.TapAPIQuotLoginRspInfo_LastLoginIP_get, _EsunnyApi.TapAPIQuotLoginRspInfo_LastLoginIP_set)
    __swig_setmethods__["LastLoginProt"] = _EsunnyApi.TapAPIQuotLoginRspInfo_LastLoginProt_set
    __swig_getmethods__["LastLoginProt"] = _EsunnyApi.TapAPIQuotLoginRspInfo_LastLoginProt_get
    if _newclass:
        LastLoginProt = _swig_property(_EsunnyApi.TapAPIQuotLoginRspInfo_LastLoginProt_get, _EsunnyApi.TapAPIQuotLoginRspInfo_LastLoginProt_set)
    __swig_setmethods__["LastLoginTime"] = _EsunnyApi.TapAPIQuotLoginRspInfo_LastLoginTime_set
    __swig_getmethods__["LastLoginTime"] = _EsunnyApi.TapAPIQuotLoginRspInfo_LastLoginTime_get
    if _newclass:
        LastLoginTime = _swig_property(_EsunnyApi.TapAPIQuotLoginRspInfo_LastLoginTime_get, _EsunnyApi.TapAPIQuotLoginRspInfo_LastLoginTime_set)
    __swig_setmethods__["LastLogoutTime"] = _EsunnyApi.TapAPIQuotLoginRspInfo_LastLogoutTime_set
    __swig_getmethods__["LastLogoutTime"] = _EsunnyApi.TapAPIQuotLoginRspInfo_LastLogoutTime_get
    if _newclass:
        LastLogoutTime = _swig_property(_EsunnyApi.TapAPIQuotLoginRspInfo_LastLogoutTime_get, _EsunnyApi.TapAPIQuotLoginRspInfo_LastLogoutTime_set)
    __swig_setmethods__["TradeDate"] = _EsunnyApi.TapAPIQuotLoginRspInfo_TradeDate_set
    __swig_getmethods__["TradeDate"] = _EsunnyApi.TapAPIQuotLoginRspInfo_TradeDate_get
    if _newclass:
        TradeDate = _swig_property(_EsunnyApi.TapAPIQuotLoginRspInfo_TradeDate_get, _EsunnyApi.TapAPIQuotLoginRspInfo_TradeDate_set)
    __swig_setmethods__["LastSettleTime"] = _EsunnyApi.TapAPIQuotLoginRspInfo_LastSettleTime_set
    __swig_getmethods__["LastSettleTime"] = _EsunnyApi.TapAPIQuotLoginRspInfo_LastSettleTime_get
    if _newclass:
        LastSettleTime = _swig_property(_EsunnyApi.TapAPIQuotLoginRspInfo_LastSettleTime_get, _EsunnyApi.TapAPIQuotLoginRspInfo_LastSettleTime_set)
    __swig_setmethods__["StartTime"] = _EsunnyApi.TapAPIQuotLoginRspInfo_StartTime_set
    __swig_getmethods__["StartTime"] = _EsunnyApi.TapAPIQuotLoginRspInfo_StartTime_get
    if _newclass:
        StartTime = _swig_property(_EsunnyApi.TapAPIQuotLoginRspInfo_StartTime_get, _EsunnyApi.TapAPIQuotLoginRspInfo_StartTime_set)
    __swig_setmethods__["InitTime"] = _EsunnyApi.TapAPIQuotLoginRspInfo_InitTime_set
    __swig_getmethods__["InitTime"] = _EsunnyApi.TapAPIQuotLoginRspInfo_InitTime_get
    if _newclass:
        InitTime = _swig_property(_EsunnyApi.TapAPIQuotLoginRspInfo_InitTime_get, _EsunnyApi.TapAPIQuotLoginRspInfo_InitTime_set)

    def __init__(self):
        this = _EsunnyApi.new_TapAPIQuotLoginRspInfo()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _EsunnyApi.delete_TapAPIQuotLoginRspInfo
    __del__ = lambda self: None
TapAPIQuotLoginRspInfo_swigregister = _EsunnyApi.TapAPIQuotLoginRspInfo_swigregister
TapAPIQuotLoginRspInfo_swigregister(TapAPIQuotLoginRspInfo)

class TapAPIQuoteCommodityInfo(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TapAPIQuoteCommodityInfo, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TapAPIQuoteCommodityInfo, name)
    __repr__ = _swig_repr
    __swig_setmethods__["Commodity"] = _EsunnyApi.TapAPIQuoteCommodityInfo_Commodity_set
    __swig_getmethods__["Commodity"] = _EsunnyApi.TapAPIQuoteCommodityInfo_Commodity_get
    if _newclass:
        Commodity = _swig_property(_EsunnyApi.TapAPIQuoteCommodityInfo_Commodity_get, _EsunnyApi.TapAPIQuoteCommodityInfo_Commodity_set)
    __swig_setmethods__["CommodityName"] = _EsunnyApi.TapAPIQuoteCommodityInfo_CommodityName_set
    __swig_getmethods__["CommodityName"] = _EsunnyApi.TapAPIQuoteCommodityInfo_CommodityName_get
    if _newclass:
        CommodityName = _swig_property(_EsunnyApi.TapAPIQuoteCommodityInfo_CommodityName_get, _EsunnyApi.TapAPIQuoteCommodityInfo_CommodityName_set)
    __swig_setmethods__["CommodityEngName"] = _EsunnyApi.TapAPIQuoteCommodityInfo_CommodityEngName_set
    __swig_getmethods__["CommodityEngName"] = _EsunnyApi.TapAPIQuoteCommodityInfo_CommodityEngName_get
    if _newclass:
        CommodityEngName = _swig_property(_EsunnyApi.TapAPIQuoteCommodityInfo_CommodityEngName_get, _EsunnyApi.TapAPIQuoteCommodityInfo_CommodityEngName_set)
    __swig_setmethods__["ContractSize"] = _EsunnyApi.TapAPIQuoteCommodityInfo_ContractSize_set
    __swig_getmethods__["ContractSize"] = _EsunnyApi.TapAPIQuoteCommodityInfo_ContractSize_get
    if _newclass:
        ContractSize = _swig_property(_EsunnyApi.TapAPIQuoteCommodityInfo_ContractSize_get, _EsunnyApi.TapAPIQuoteCommodityInfo_ContractSize_set)
    __swig_setmethods__["CommodityTickSize"] = _EsunnyApi.TapAPIQuoteCommodityInfo_CommodityTickSize_set
    __swig_getmethods__["CommodityTickSize"] = _EsunnyApi.TapAPIQuoteCommodityInfo_CommodityTickSize_get
    if _newclass:
        CommodityTickSize = _swig_property(_EsunnyApi.TapAPIQuoteCommodityInfo_CommodityTickSize_get, _EsunnyApi.TapAPIQuoteCommodityInfo_CommodityTickSize_set)
    __swig_setmethods__["CommodityDenominator"] = _EsunnyApi.TapAPIQuoteCommodityInfo_CommodityDenominator_set
    __swig_getmethods__["CommodityDenominator"] = _EsunnyApi.TapAPIQuoteCommodityInfo_CommodityDenominator_get
    if _newclass:
        CommodityDenominator = _swig_property(_EsunnyApi.TapAPIQuoteCommodityInfo_CommodityDenominator_get, _EsunnyApi.TapAPIQuoteCommodityInfo_CommodityDenominator_set)
    __swig_setmethods__["CmbDirect"] = _EsunnyApi.TapAPIQuoteCommodityInfo_CmbDirect_set
    __swig_getmethods__["CmbDirect"] = _EsunnyApi.TapAPIQuoteCommodityInfo_CmbDirect_get
    if _newclass:
        CmbDirect = _swig_property(_EsunnyApi.TapAPIQuoteCommodityInfo_CmbDirect_get, _EsunnyApi.TapAPIQuoteCommodityInfo_CmbDirect_set)
    __swig_setmethods__["CommodityContractLen"] = _EsunnyApi.TapAPIQuoteCommodityInfo_CommodityContractLen_set
    __swig_getmethods__["CommodityContractLen"] = _EsunnyApi.TapAPIQuoteCommodityInfo_CommodityContractLen_get
    if _newclass:
        CommodityContractLen = _swig_property(_EsunnyApi.TapAPIQuoteCommodityInfo_CommodityContractLen_get, _EsunnyApi.TapAPIQuoteCommodityInfo_CommodityContractLen_set)
    __swig_setmethods__["IsDST"] = _EsunnyApi.TapAPIQuoteCommodityInfo_IsDST_set
    __swig_getmethods__["IsDST"] = _EsunnyApi.TapAPIQuoteCommodityInfo_IsDST_get
    if _newclass:
        IsDST = _swig_property(_EsunnyApi.TapAPIQuoteCommodityInfo_IsDST_get, _EsunnyApi.TapAPIQuoteCommodityInfo_IsDST_set)
    __swig_setmethods__["RelateCommodity1"] = _EsunnyApi.TapAPIQuoteCommodityInfo_RelateCommodity1_set
    __swig_getmethods__["RelateCommodity1"] = _EsunnyApi.TapAPIQuoteCommodityInfo_RelateCommodity1_get
    if _newclass:
        RelateCommodity1 = _swig_property(_EsunnyApi.TapAPIQuoteCommodityInfo_RelateCommodity1_get, _EsunnyApi.TapAPIQuoteCommodityInfo_RelateCommodity1_set)
    __swig_setmethods__["RelateCommodity2"] = _EsunnyApi.TapAPIQuoteCommodityInfo_RelateCommodity2_set
    __swig_getmethods__["RelateCommodity2"] = _EsunnyApi.TapAPIQuoteCommodityInfo_RelateCommodity2_get
    if _newclass:
        RelateCommodity2 = _swig_property(_EsunnyApi.TapAPIQuoteCommodityInfo_RelateCommodity2_get, _EsunnyApi.TapAPIQuoteCommodityInfo_RelateCommodity2_set)

    def __init__(self):
        this = _EsunnyApi.new_TapAPIQuoteCommodityInfo()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _EsunnyApi.delete_TapAPIQuoteCommodityInfo
    __del__ = lambda self: None
TapAPIQuoteCommodityInfo_swigregister = _EsunnyApi.TapAPIQuoteCommodityInfo_swigregister
TapAPIQuoteCommodityInfo_swigregister(TapAPIQuoteCommodityInfo)

class TapAPIQuoteContractInfo(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TapAPIQuoteContractInfo, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TapAPIQuoteContractInfo, name)
    __repr__ = _swig_repr
    __swig_setmethods__["Contract"] = _EsunnyApi.TapAPIQuoteContractInfo_Contract_set
    __swig_getmethods__["Contract"] = _EsunnyApi.TapAPIQuoteContractInfo_Contract_get
    if _newclass:
        Contract = _swig_property(_EsunnyApi.TapAPIQuoteContractInfo_Contract_get, _EsunnyApi.TapAPIQuoteContractInfo_Contract_set)
    __swig_setmethods__["ContractType"] = _EsunnyApi.TapAPIQuoteContractInfo_ContractType_set
    __swig_getmethods__["ContractType"] = _EsunnyApi.TapAPIQuoteContractInfo_ContractType_get
    if _newclass:
        ContractType = _swig_property(_EsunnyApi.TapAPIQuoteContractInfo_ContractType_get, _EsunnyApi.TapAPIQuoteContractInfo_ContractType_set)
    __swig_setmethods__["QuoteUnderlyingContract"] = _EsunnyApi.TapAPIQuoteContractInfo_QuoteUnderlyingContract_set
    __swig_getmethods__["QuoteUnderlyingContract"] = _EsunnyApi.TapAPIQuoteContractInfo_QuoteUnderlyingContract_get
    if _newclass:
        QuoteUnderlyingContract = _swig_property(_EsunnyApi.TapAPIQuoteContractInfo_QuoteUnderlyingContract_get, _EsunnyApi.TapAPIQuoteContractInfo_QuoteUnderlyingContract_set)
    __swig_setmethods__["ContractName"] = _EsunnyApi.TapAPIQuoteContractInfo_ContractName_set
    __swig_getmethods__["ContractName"] = _EsunnyApi.TapAPIQuoteContractInfo_ContractName_get
    if _newclass:
        ContractName = _swig_property(_EsunnyApi.TapAPIQuoteContractInfo_ContractName_get, _EsunnyApi.TapAPIQuoteContractInfo_ContractName_set)
    __swig_setmethods__["ContractExpDate"] = _EsunnyApi.TapAPIQuoteContractInfo_ContractExpDate_set
    __swig_getmethods__["ContractExpDate"] = _EsunnyApi.TapAPIQuoteContractInfo_ContractExpDate_get
    if _newclass:
        ContractExpDate = _swig_property(_EsunnyApi.TapAPIQuoteContractInfo_ContractExpDate_get, _EsunnyApi.TapAPIQuoteContractInfo_ContractExpDate_set)
    __swig_setmethods__["LastTradeDate"] = _EsunnyApi.TapAPIQuoteContractInfo_LastTradeDate_set
    __swig_getmethods__["LastTradeDate"] = _EsunnyApi.TapAPIQuoteContractInfo_LastTradeDate_get
    if _newclass:
        LastTradeDate = _swig_property(_EsunnyApi.TapAPIQuoteContractInfo_LastTradeDate_get, _EsunnyApi.TapAPIQuoteContractInfo_LastTradeDate_set)
    __swig_setmethods__["FirstNoticeDate"] = _EsunnyApi.TapAPIQuoteContractInfo_FirstNoticeDate_set
    __swig_getmethods__["FirstNoticeDate"] = _EsunnyApi.TapAPIQuoteContractInfo_FirstNoticeDate_get
    if _newclass:
        FirstNoticeDate = _swig_property(_EsunnyApi.TapAPIQuoteContractInfo_FirstNoticeDate_get, _EsunnyApi.TapAPIQuoteContractInfo_FirstNoticeDate_set)

    def __init__(self):
        this = _EsunnyApi.new_TapAPIQuoteContractInfo()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _EsunnyApi.delete_TapAPIQuoteContractInfo
    __del__ = lambda self: None
TapAPIQuoteContractInfo_swigregister = _EsunnyApi.TapAPIQuoteContractInfo_swigregister
TapAPIQuoteContractInfo_swigregister(TapAPIQuoteContractInfo)

class TapAPIQuoteWhole(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TapAPIQuoteWhole, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TapAPIQuoteWhole, name)
    __repr__ = _swig_repr
    __swig_setmethods__["Contract"] = _EsunnyApi.TapAPIQuoteWhole_Contract_set
    __swig_getmethods__["Contract"] = _EsunnyApi.TapAPIQuoteWhole_Contract_get
    if _newclass:
        Contract = _swig_property(_EsunnyApi.TapAPIQuoteWhole_Contract_get, _EsunnyApi.TapAPIQuoteWhole_Contract_set)
    __swig_setmethods__["CurrencyNo"] = _EsunnyApi.TapAPIQuoteWhole_CurrencyNo_set
    __swig_getmethods__["CurrencyNo"] = _EsunnyApi.TapAPIQuoteWhole_CurrencyNo_get
    if _newclass:
        CurrencyNo = _swig_property(_EsunnyApi.TapAPIQuoteWhole_CurrencyNo_get, _EsunnyApi.TapAPIQuoteWhole_CurrencyNo_set)
    __swig_setmethods__["TradingState"] = _EsunnyApi.TapAPIQuoteWhole_TradingState_set
    __swig_getmethods__["TradingState"] = _EsunnyApi.TapAPIQuoteWhole_TradingState_get
    if _newclass:
        TradingState = _swig_property(_EsunnyApi.TapAPIQuoteWhole_TradingState_get, _EsunnyApi.TapAPIQuoteWhole_TradingState_set)
    __swig_setmethods__["DateTimeStamp"] = _EsunnyApi.TapAPIQuoteWhole_DateTimeStamp_set
    __swig_getmethods__["DateTimeStamp"] = _EsunnyApi.TapAPIQuoteWhole_DateTimeStamp_get
    if _newclass:
        DateTimeStamp = _swig_property(_EsunnyApi.TapAPIQuoteWhole_DateTimeStamp_get, _EsunnyApi.TapAPIQuoteWhole_DateTimeStamp_set)
    __swig_setmethods__["QPreClosingPrice"] = _EsunnyApi.TapAPIQuoteWhole_QPreClosingPrice_set
    __swig_getmethods__["QPreClosingPrice"] = _EsunnyApi.TapAPIQuoteWhole_QPreClosingPrice_get
    if _newclass:
        QPreClosingPrice = _swig_property(_EsunnyApi.TapAPIQuoteWhole_QPreClosingPrice_get, _EsunnyApi.TapAPIQuoteWhole_QPreClosingPrice_set)
    __swig_setmethods__["QPreSettlePrice"] = _EsunnyApi.TapAPIQuoteWhole_QPreSettlePrice_set
    __swig_getmethods__["QPreSettlePrice"] = _EsunnyApi.TapAPIQuoteWhole_QPreSettlePrice_get
    if _newclass:
        QPreSettlePrice = _swig_property(_EsunnyApi.TapAPIQuoteWhole_QPreSettlePrice_get, _EsunnyApi.TapAPIQuoteWhole_QPreSettlePrice_set)
    __swig_setmethods__["QPrePositionQty"] = _EsunnyApi.TapAPIQuoteWhole_QPrePositionQty_set
    __swig_getmethods__["QPrePositionQty"] = _EsunnyApi.TapAPIQuoteWhole_QPrePositionQty_get
    if _newclass:
        QPrePositionQty = _swig_property(_EsunnyApi.TapAPIQuoteWhole_QPrePositionQty_get, _EsunnyApi.TapAPIQuoteWhole_QPrePositionQty_set)
    __swig_setmethods__["QOpeningPrice"] = _EsunnyApi.TapAPIQuoteWhole_QOpeningPrice_set
    __swig_getmethods__["QOpeningPrice"] = _EsunnyApi.TapAPIQuoteWhole_QOpeningPrice_get
    if _newclass:
        QOpeningPrice = _swig_property(_EsunnyApi.TapAPIQuoteWhole_QOpeningPrice_get, _EsunnyApi.TapAPIQuoteWhole_QOpeningPrice_set)
    __swig_setmethods__["QLastPrice"] = _EsunnyApi.TapAPIQuoteWhole_QLastPrice_set
    __swig_getmethods__["QLastPrice"] = _EsunnyApi.TapAPIQuoteWhole_QLastPrice_get
    if _newclass:
        QLastPrice = _swig_property(_EsunnyApi.TapAPIQuoteWhole_QLastPrice_get, _EsunnyApi.TapAPIQuoteWhole_QLastPrice_set)
    __swig_setmethods__["QHighPrice"] = _EsunnyApi.TapAPIQuoteWhole_QHighPrice_set
    __swig_getmethods__["QHighPrice"] = _EsunnyApi.TapAPIQuoteWhole_QHighPrice_get
    if _newclass:
        QHighPrice = _swig_property(_EsunnyApi.TapAPIQuoteWhole_QHighPrice_get, _EsunnyApi.TapAPIQuoteWhole_QHighPrice_set)
    __swig_setmethods__["QLowPrice"] = _EsunnyApi.TapAPIQuoteWhole_QLowPrice_set
    __swig_getmethods__["QLowPrice"] = _EsunnyApi.TapAPIQuoteWhole_QLowPrice_get
    if _newclass:
        QLowPrice = _swig_property(_EsunnyApi.TapAPIQuoteWhole_QLowPrice_get, _EsunnyApi.TapAPIQuoteWhole_QLowPrice_set)
    __swig_setmethods__["QHisHighPrice"] = _EsunnyApi.TapAPIQuoteWhole_QHisHighPrice_set
    __swig_getmethods__["QHisHighPrice"] = _EsunnyApi.TapAPIQuoteWhole_QHisHighPrice_get
    if _newclass:
        QHisHighPrice = _swig_property(_EsunnyApi.TapAPIQuoteWhole_QHisHighPrice_get, _EsunnyApi.TapAPIQuoteWhole_QHisHighPrice_set)
    __swig_setmethods__["QHisLowPrice"] = _EsunnyApi.TapAPIQuoteWhole_QHisLowPrice_set
    __swig_getmethods__["QHisLowPrice"] = _EsunnyApi.TapAPIQuoteWhole_QHisLowPrice_get
    if _newclass:
        QHisLowPrice = _swig_property(_EsunnyApi.TapAPIQuoteWhole_QHisLowPrice_get, _EsunnyApi.TapAPIQuoteWhole_QHisLowPrice_set)
    __swig_setmethods__["QLimitUpPrice"] = _EsunnyApi.TapAPIQuoteWhole_QLimitUpPrice_set
    __swig_getmethods__["QLimitUpPrice"] = _EsunnyApi.TapAPIQuoteWhole_QLimitUpPrice_get
    if _newclass:
        QLimitUpPrice = _swig_property(_EsunnyApi.TapAPIQuoteWhole_QLimitUpPrice_get, _EsunnyApi.TapAPIQuoteWhole_QLimitUpPrice_set)
    __swig_setmethods__["QLimitDownPrice"] = _EsunnyApi.TapAPIQuoteWhole_QLimitDownPrice_set
    __swig_getmethods__["QLimitDownPrice"] = _EsunnyApi.TapAPIQuoteWhole_QLimitDownPrice_get
    if _newclass:
        QLimitDownPrice = _swig_property(_EsunnyApi.TapAPIQuoteWhole_QLimitDownPrice_get, _EsunnyApi.TapAPIQuoteWhole_QLimitDownPrice_set)
    __swig_setmethods__["QTotalQty"] = _EsunnyApi.TapAPIQuoteWhole_QTotalQty_set
    __swig_getmethods__["QTotalQty"] = _EsunnyApi.TapAPIQuoteWhole_QTotalQty_get
    if _newclass:
        QTotalQty = _swig_property(_EsunnyApi.TapAPIQuoteWhole_QTotalQty_get, _EsunnyApi.TapAPIQuoteWhole_QTotalQty_set)
    __swig_setmethods__["QTotalTurnover"] = _EsunnyApi.TapAPIQuoteWhole_QTotalTurnover_set
    __swig_getmethods__["QTotalTurnover"] = _EsunnyApi.TapAPIQuoteWhole_QTotalTurnover_get
    if _newclass:
        QTotalTurnover = _swig_property(_EsunnyApi.TapAPIQuoteWhole_QTotalTurnover_get, _EsunnyApi.TapAPIQuoteWhole_QTotalTurnover_set)
    __swig_setmethods__["QPositionQty"] = _EsunnyApi.TapAPIQuoteWhole_QPositionQty_set
    __swig_getmethods__["QPositionQty"] = _EsunnyApi.TapAPIQuoteWhole_QPositionQty_get
    if _newclass:
        QPositionQty = _swig_property(_EsunnyApi.TapAPIQuoteWhole_QPositionQty_get, _EsunnyApi.TapAPIQuoteWhole_QPositionQty_set)
    __swig_setmethods__["QAveragePrice"] = _EsunnyApi.TapAPIQuoteWhole_QAveragePrice_set
    __swig_getmethods__["QAveragePrice"] = _EsunnyApi.TapAPIQuoteWhole_QAveragePrice_get
    if _newclass:
        QAveragePrice = _swig_property(_EsunnyApi.TapAPIQuoteWhole_QAveragePrice_get, _EsunnyApi.TapAPIQuoteWhole_QAveragePrice_set)
    __swig_setmethods__["QClosingPrice"] = _EsunnyApi.TapAPIQuoteWhole_QClosingPrice_set
    __swig_getmethods__["QClosingPrice"] = _EsunnyApi.TapAPIQuoteWhole_QClosingPrice_get
    if _newclass:
        QClosingPrice = _swig_property(_EsunnyApi.TapAPIQuoteWhole_QClosingPrice_get, _EsunnyApi.TapAPIQuoteWhole_QClosingPrice_set)
    __swig_setmethods__["QSettlePrice"] = _EsunnyApi.TapAPIQuoteWhole_QSettlePrice_set
    __swig_getmethods__["QSettlePrice"] = _EsunnyApi.TapAPIQuoteWhole_QSettlePrice_get
    if _newclass:
        QSettlePrice = _swig_property(_EsunnyApi.TapAPIQuoteWhole_QSettlePrice_get, _EsunnyApi.TapAPIQuoteWhole_QSettlePrice_set)
    __swig_setmethods__["QLastQty"] = _EsunnyApi.TapAPIQuoteWhole_QLastQty_set
    __swig_getmethods__["QLastQty"] = _EsunnyApi.TapAPIQuoteWhole_QLastQty_get
    if _newclass:
        QLastQty = _swig_property(_EsunnyApi.TapAPIQuoteWhole_QLastQty_get, _EsunnyApi.TapAPIQuoteWhole_QLastQty_set)
    __swig_setmethods__["QBidPrice"] = _EsunnyApi.TapAPIQuoteWhole_QBidPrice_set
    __swig_getmethods__["QBidPrice"] = _EsunnyApi.TapAPIQuoteWhole_QBidPrice_get
    if _newclass:
        QBidPrice = _swig_property(_EsunnyApi.TapAPIQuoteWhole_QBidPrice_get, _EsunnyApi.TapAPIQuoteWhole_QBidPrice_set)
    __swig_setmethods__["QBidQty"] = _EsunnyApi.TapAPIQuoteWhole_QBidQty_set
    __swig_getmethods__["QBidQty"] = _EsunnyApi.TapAPIQuoteWhole_QBidQty_get
    if _newclass:
        QBidQty = _swig_property(_EsunnyApi.TapAPIQuoteWhole_QBidQty_get, _EsunnyApi.TapAPIQuoteWhole_QBidQty_set)
    __swig_setmethods__["QAskPrice"] = _EsunnyApi.TapAPIQuoteWhole_QAskPrice_set
    __swig_getmethods__["QAskPrice"] = _EsunnyApi.TapAPIQuoteWhole_QAskPrice_get
    if _newclass:
        QAskPrice = _swig_property(_EsunnyApi.TapAPIQuoteWhole_QAskPrice_get, _EsunnyApi.TapAPIQuoteWhole_QAskPrice_set)
    __swig_setmethods__["QAskQty"] = _EsunnyApi.TapAPIQuoteWhole_QAskQty_set
    __swig_getmethods__["QAskQty"] = _EsunnyApi.TapAPIQuoteWhole_QAskQty_get
    if _newclass:
        QAskQty = _swig_property(_EsunnyApi.TapAPIQuoteWhole_QAskQty_get, _EsunnyApi.TapAPIQuoteWhole_QAskQty_set)
    __swig_setmethods__["QImpliedBidPrice"] = _EsunnyApi.TapAPIQuoteWhole_QImpliedBidPrice_set
    __swig_getmethods__["QImpliedBidPrice"] = _EsunnyApi.TapAPIQuoteWhole_QImpliedBidPrice_get
    if _newclass:
        QImpliedBidPrice = _swig_property(_EsunnyApi.TapAPIQuoteWhole_QImpliedBidPrice_get, _EsunnyApi.TapAPIQuoteWhole_QImpliedBidPrice_set)
    __swig_setmethods__["QImpliedBidQty"] = _EsunnyApi.TapAPIQuoteWhole_QImpliedBidQty_set
    __swig_getmethods__["QImpliedBidQty"] = _EsunnyApi.TapAPIQuoteWhole_QImpliedBidQty_get
    if _newclass:
        QImpliedBidQty = _swig_property(_EsunnyApi.TapAPIQuoteWhole_QImpliedBidQty_get, _EsunnyApi.TapAPIQuoteWhole_QImpliedBidQty_set)
    __swig_setmethods__["QImpliedAskPrice"] = _EsunnyApi.TapAPIQuoteWhole_QImpliedAskPrice_set
    __swig_getmethods__["QImpliedAskPrice"] = _EsunnyApi.TapAPIQuoteWhole_QImpliedAskPrice_get
    if _newclass:
        QImpliedAskPrice = _swig_property(_EsunnyApi.TapAPIQuoteWhole_QImpliedAskPrice_get, _EsunnyApi.TapAPIQuoteWhole_QImpliedAskPrice_set)
    __swig_setmethods__["QImpliedAskQty"] = _EsunnyApi.TapAPIQuoteWhole_QImpliedAskQty_set
    __swig_getmethods__["QImpliedAskQty"] = _EsunnyApi.TapAPIQuoteWhole_QImpliedAskQty_get
    if _newclass:
        QImpliedAskQty = _swig_property(_EsunnyApi.TapAPIQuoteWhole_QImpliedAskQty_get, _EsunnyApi.TapAPIQuoteWhole_QImpliedAskQty_set)
    __swig_setmethods__["QPreDelta"] = _EsunnyApi.TapAPIQuoteWhole_QPreDelta_set
    __swig_getmethods__["QPreDelta"] = _EsunnyApi.TapAPIQuoteWhole_QPreDelta_get
    if _newclass:
        QPreDelta = _swig_property(_EsunnyApi.TapAPIQuoteWhole_QPreDelta_get, _EsunnyApi.TapAPIQuoteWhole_QPreDelta_set)
    __swig_setmethods__["QCurrDelta"] = _EsunnyApi.TapAPIQuoteWhole_QCurrDelta_set
    __swig_getmethods__["QCurrDelta"] = _EsunnyApi.TapAPIQuoteWhole_QCurrDelta_get
    if _newclass:
        QCurrDelta = _swig_property(_EsunnyApi.TapAPIQuoteWhole_QCurrDelta_get, _EsunnyApi.TapAPIQuoteWhole_QCurrDelta_set)
    __swig_setmethods__["QInsideQty"] = _EsunnyApi.TapAPIQuoteWhole_QInsideQty_set
    __swig_getmethods__["QInsideQty"] = _EsunnyApi.TapAPIQuoteWhole_QInsideQty_get
    if _newclass:
        QInsideQty = _swig_property(_EsunnyApi.TapAPIQuoteWhole_QInsideQty_get, _EsunnyApi.TapAPIQuoteWhole_QInsideQty_set)
    __swig_setmethods__["QOutsideQty"] = _EsunnyApi.TapAPIQuoteWhole_QOutsideQty_set
    __swig_getmethods__["QOutsideQty"] = _EsunnyApi.TapAPIQuoteWhole_QOutsideQty_get
    if _newclass:
        QOutsideQty = _swig_property(_EsunnyApi.TapAPIQuoteWhole_QOutsideQty_get, _EsunnyApi.TapAPIQuoteWhole_QOutsideQty_set)
    __swig_setmethods__["QTurnoverRate"] = _EsunnyApi.TapAPIQuoteWhole_QTurnoverRate_set
    __swig_getmethods__["QTurnoverRate"] = _EsunnyApi.TapAPIQuoteWhole_QTurnoverRate_get
    if _newclass:
        QTurnoverRate = _swig_property(_EsunnyApi.TapAPIQuoteWhole_QTurnoverRate_get, _EsunnyApi.TapAPIQuoteWhole_QTurnoverRate_set)
    __swig_setmethods__["Q5DAvgQty"] = _EsunnyApi.TapAPIQuoteWhole_Q5DAvgQty_set
    __swig_getmethods__["Q5DAvgQty"] = _EsunnyApi.TapAPIQuoteWhole_Q5DAvgQty_get
    if _newclass:
        Q5DAvgQty = _swig_property(_EsunnyApi.TapAPIQuoteWhole_Q5DAvgQty_get, _EsunnyApi.TapAPIQuoteWhole_Q5DAvgQty_set)
    __swig_setmethods__["QPERatio"] = _EsunnyApi.TapAPIQuoteWhole_QPERatio_set
    __swig_getmethods__["QPERatio"] = _EsunnyApi.TapAPIQuoteWhole_QPERatio_get
    if _newclass:
        QPERatio = _swig_property(_EsunnyApi.TapAPIQuoteWhole_QPERatio_get, _EsunnyApi.TapAPIQuoteWhole_QPERatio_set)
    __swig_setmethods__["QTotalValue"] = _EsunnyApi.TapAPIQuoteWhole_QTotalValue_set
    __swig_getmethods__["QTotalValue"] = _EsunnyApi.TapAPIQuoteWhole_QTotalValue_get
    if _newclass:
        QTotalValue = _swig_property(_EsunnyApi.TapAPIQuoteWhole_QTotalValue_get, _EsunnyApi.TapAPIQuoteWhole_QTotalValue_set)
    __swig_setmethods__["QNegotiableValue"] = _EsunnyApi.TapAPIQuoteWhole_QNegotiableValue_set
    __swig_getmethods__["QNegotiableValue"] = _EsunnyApi.TapAPIQuoteWhole_QNegotiableValue_get
    if _newclass:
        QNegotiableValue = _swig_property(_EsunnyApi.TapAPIQuoteWhole_QNegotiableValue_get, _EsunnyApi.TapAPIQuoteWhole_QNegotiableValue_set)
    __swig_setmethods__["QPositionTrend"] = _EsunnyApi.TapAPIQuoteWhole_QPositionTrend_set
    __swig_getmethods__["QPositionTrend"] = _EsunnyApi.TapAPIQuoteWhole_QPositionTrend_get
    if _newclass:
        QPositionTrend = _swig_property(_EsunnyApi.TapAPIQuoteWhole_QPositionTrend_get, _EsunnyApi.TapAPIQuoteWhole_QPositionTrend_set)
    __swig_setmethods__["QChangeSpeed"] = _EsunnyApi.TapAPIQuoteWhole_QChangeSpeed_set
    __swig_getmethods__["QChangeSpeed"] = _EsunnyApi.TapAPIQuoteWhole_QChangeSpeed_get
    if _newclass:
        QChangeSpeed = _swig_property(_EsunnyApi.TapAPIQuoteWhole_QChangeSpeed_get, _EsunnyApi.TapAPIQuoteWhole_QChangeSpeed_set)
    __swig_setmethods__["QChangeRate"] = _EsunnyApi.TapAPIQuoteWhole_QChangeRate_set
    __swig_getmethods__["QChangeRate"] = _EsunnyApi.TapAPIQuoteWhole_QChangeRate_get
    if _newclass:
        QChangeRate = _swig_property(_EsunnyApi.TapAPIQuoteWhole_QChangeRate_get, _EsunnyApi.TapAPIQuoteWhole_QChangeRate_set)
    __swig_setmethods__["QChangeValue"] = _EsunnyApi.TapAPIQuoteWhole_QChangeValue_set
    __swig_getmethods__["QChangeValue"] = _EsunnyApi.TapAPIQuoteWhole_QChangeValue_get
    if _newclass:
        QChangeValue = _swig_property(_EsunnyApi.TapAPIQuoteWhole_QChangeValue_get, _EsunnyApi.TapAPIQuoteWhole_QChangeValue_set)
    __swig_setmethods__["QSwing"] = _EsunnyApi.TapAPIQuoteWhole_QSwing_set
    __swig_getmethods__["QSwing"] = _EsunnyApi.TapAPIQuoteWhole_QSwing_get
    if _newclass:
        QSwing = _swig_property(_EsunnyApi.TapAPIQuoteWhole_QSwing_get, _EsunnyApi.TapAPIQuoteWhole_QSwing_set)
    __swig_setmethods__["QTotalBidQty"] = _EsunnyApi.TapAPIQuoteWhole_QTotalBidQty_set
    __swig_getmethods__["QTotalBidQty"] = _EsunnyApi.TapAPIQuoteWhole_QTotalBidQty_get
    if _newclass:
        QTotalBidQty = _swig_property(_EsunnyApi.TapAPIQuoteWhole_QTotalBidQty_get, _EsunnyApi.TapAPIQuoteWhole_QTotalBidQty_set)
    __swig_setmethods__["QTotalAskQty"] = _EsunnyApi.TapAPIQuoteWhole_QTotalAskQty_set
    __swig_getmethods__["QTotalAskQty"] = _EsunnyApi.TapAPIQuoteWhole_QTotalAskQty_get
    if _newclass:
        QTotalAskQty = _swig_property(_EsunnyApi.TapAPIQuoteWhole_QTotalAskQty_get, _EsunnyApi.TapAPIQuoteWhole_QTotalAskQty_set)
    __swig_setmethods__["UnderlyContract"] = _EsunnyApi.TapAPIQuoteWhole_UnderlyContract_set
    __swig_getmethods__["UnderlyContract"] = _EsunnyApi.TapAPIQuoteWhole_UnderlyContract_get
    if _newclass:
        UnderlyContract = _swig_property(_EsunnyApi.TapAPIQuoteWhole_UnderlyContract_get, _EsunnyApi.TapAPIQuoteWhole_UnderlyContract_set)

    def __init__(self):
        this = _EsunnyApi.new_TapAPIQuoteWhole()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _EsunnyApi.delete_TapAPIQuoteWhole
    __del__ = lambda self: None
TapAPIQuoteWhole_swigregister = _EsunnyApi.TapAPIQuoteWhole_swigregister
TapAPIQuoteWhole_swigregister(TapAPIQuoteWhole)

class ITapQuoteAPINotify(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ITapQuoteAPINotify, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ITapQuoteAPINotify, name)
    __repr__ = _swig_repr

    def OnRspLogin(self, errorCode, info):
        return _EsunnyApi.ITapQuoteAPINotify_OnRspLogin(self, errorCode, info)

    def OnAPIReady(self):
        return _EsunnyApi.ITapQuoteAPINotify_OnAPIReady(self)

    def OnDisconnect(self, reasonCode):
        return _EsunnyApi.ITapQuoteAPINotify_OnDisconnect(self, reasonCode)

    def OnRspQryCommodity(self, sessionID, errorCode, isLast, info):
        return _EsunnyApi.ITapQuoteAPINotify_OnRspQryCommodity(self, sessionID, errorCode, isLast, info)

    def OnRspQryContract(self, sessionID, errorCode, isLast, info):
        return _EsunnyApi.ITapQuoteAPINotify_OnRspQryContract(self, sessionID, errorCode, isLast, info)

    def OnRspSubscribeQuote(self, sessionID, errorCode, isLast, info):
        return _EsunnyApi.ITapQuoteAPINotify_OnRspSubscribeQuote(self, sessionID, errorCode, isLast, info)

    def OnRspUnSubscribeQuote(self, sessionID, errorCode, isLast, info):
        return _EsunnyApi.ITapQuoteAPINotify_OnRspUnSubscribeQuote(self, sessionID, errorCode, isLast, info)

    def OnRtnQuote(self, info):
        return _EsunnyApi.ITapQuoteAPINotify_OnRtnQuote(self, info)

    def __init__(self):
        if self.__class__ == ITapQuoteAPINotify:
            _self = None
        else:
            _self = self
        this = _EsunnyApi.new_ITapQuoteAPINotify(_self, )
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _EsunnyApi.delete_ITapQuoteAPINotify
    __del__ = lambda self: None
    def __disown__(self):
        self.this.disown()
        _EsunnyApi.disown_ITapQuoteAPINotify(self)
        return weakref_proxy(self)
ITapQuoteAPINotify_swigregister = _EsunnyApi.ITapQuoteAPINotify_swigregister
ITapQuoteAPINotify_swigregister(ITapQuoteAPINotify)
TAPIERROR_SUCCEED = cvar.TAPIERROR_SUCCEED
TAPIERROR_ConnectFail = cvar.TAPIERROR_ConnectFail
TAPIERROR_LinkAuthFail = cvar.TAPIERROR_LinkAuthFail
TAPIERROR_HostUnavailable = cvar.TAPIERROR_HostUnavailable
TAPIERROR_SendDataError = cvar.TAPIERROR_SendDataError
TAPIERROR_TestIDError = cvar.TAPIERROR_TestIDError
TAPIERROR_NotReadyTestNetwork = cvar.TAPIERROR_NotReadyTestNetwork
TAPIERROR_CurTestNotOver = cvar.TAPIERROR_CurTestNotOver
TAPIERROR_NOFrontAvailable = cvar.TAPIERROR_NOFrontAvailable
TAPIERROR_DataPathAvaiable = cvar.TAPIERROR_DataPathAvaiable
TAPIERROR_RepeatLogin = cvar.TAPIERROR_RepeatLogin
TAPIERROR_InnerError = cvar.TAPIERROR_InnerError
TAPIERROR_LastReqNotFinish = cvar.TAPIERROR_LastReqNotFinish
TAPIERROR_InputValueError = cvar.TAPIERROR_InputValueError
TAPIERROR_AuthCode_Invalid = cvar.TAPIERROR_AuthCode_Invalid
TAPIERROR_AuthCode_Expired = cvar.TAPIERROR_AuthCode_Expired
TAPIERROR_AuthCode_TypeNotMatch = cvar.TAPIERROR_AuthCode_TypeNotMatch
TAPIERROR_API_NotReady = cvar.TAPIERROR_API_NotReady
TAPIERROR_UDP_LISTEN_FAILED = cvar.TAPIERROR_UDP_LISTEN_FAILED
TAPIERROR_UDP_LISTENING = cvar.TAPIERROR_UDP_LISTENING
TAPIERROR_NotImplemented = cvar.TAPIERROR_NotImplemented
TAPIERROR_CallOneTimeOnly = cvar.TAPIERROR_CallOneTimeOnly
TAPIERROR_Frequently = cvar.TAPIERROR_Frequently
TAPIERROR_DataCollect = cvar.TAPIERROR_DataCollect
TAPIERROR_DataLoad = cvar.TAPIERROR_DataLoad
TAPIERROR_NoRelay = cvar.TAPIERROR_NoRelay
TAPIERROR_INPUTERROR_NULL = cvar.TAPIERROR_INPUTERROR_NULL
TAPIERROR_INPUTERROR_TAPIYNFLAG = cvar.TAPIERROR_INPUTERROR_TAPIYNFLAG
TAPIERROR_INPUTERROR_TAPILOGLEVEL = cvar.TAPIERROR_INPUTERROR_TAPILOGLEVEL
TAPIERROR_INPUTERROR_TAPICommodityType = cvar.TAPIERROR_INPUTERROR_TAPICommodityType
TAPIERROR_INPUTERROR_TAPICallOrPutFlagType = cvar.TAPIERROR_INPUTERROR_TAPICallOrPutFlagType
TAPIERROR_INPUTERROR_TAPIAccountType = cvar.TAPIERROR_INPUTERROR_TAPIAccountType
TAPIERROR_INPUTERROR_TAPIAccountState = cvar.TAPIERROR_INPUTERROR_TAPIAccountState
TAPIERROR_INPUTERROR_TAPIAccountFamilyType = cvar.TAPIERROR_INPUTERROR_TAPIAccountFamilyType
TAPIERROR_INPUTERROR_TAPIOrderTypeType = cvar.TAPIERROR_INPUTERROR_TAPIOrderTypeType
TAPIERROR_INPUTERROR_TAPIOrderSourceType = cvar.TAPIERROR_INPUTERROR_TAPIOrderSourceType
TAPIERROR_INPUTERROR_TAPITimeInForceType = cvar.TAPIERROR_INPUTERROR_TAPITimeInForceType
TAPIERROR_INPUTERROR_TAPISideType = cvar.TAPIERROR_INPUTERROR_TAPISideType
TAPIERROR_INPUTERROR_TAPIPositionEffectType = cvar.TAPIERROR_INPUTERROR_TAPIPositionEffectType
TAPIERROR_INPUTERROR_TAPIHedgeFlagType = cvar.TAPIERROR_INPUTERROR_TAPIHedgeFlagType
TAPIERROR_INPUTERROR_TAPIOrderStateType = cvar.TAPIERROR_INPUTERROR_TAPIOrderStateType
TAPIERROR_INPUTERROR_TAPICalculateModeType = cvar.TAPIERROR_INPUTERROR_TAPICalculateModeType
TAPIERROR_INPUTERROR_TAPIMatchSourceType = cvar.TAPIERROR_INPUTERROR_TAPIMatchSourceType
TAPIERROR_INPUTERROR_TAPIOpenCloseModeType = cvar.TAPIERROR_INPUTERROR_TAPIOpenCloseModeType
TAPIERROR_INPUTERROR_TAPIFutureAlgType = cvar.TAPIERROR_INPUTERROR_TAPIFutureAlgType
TAPIERROR_INPUTERROR_TAPIOptionAlgType = cvar.TAPIERROR_INPUTERROR_TAPIOptionAlgType
TAPIERROR_INPUTERROR_TAPIBankAccountLWFlagType = cvar.TAPIERROR_INPUTERROR_TAPIBankAccountLWFlagType
TAPIERROR_INPUTERROR_TAPIMarginCalculateModeType = cvar.TAPIERROR_INPUTERROR_TAPIMarginCalculateModeType
TAPIERROR_INPUTERROR_TAPIOptionMarginCalculateModeType = cvar.TAPIERROR_INPUTERROR_TAPIOptionMarginCalculateModeType
TAPIERROR_INPUTERROR_TAPICmbDirectType = cvar.TAPIERROR_INPUTERROR_TAPICmbDirectType
TAPIERROR_INPUTERROR_TAPIDeliveryModeType = cvar.TAPIERROR_INPUTERROR_TAPIDeliveryModeType
TAPIERROR_INPUTERROR_TAPIContractTypeType = cvar.TAPIERROR_INPUTERROR_TAPIContractTypeType
TAPIERROR_INPUTERROR_TAPITacticsTypeType = cvar.TAPIERROR_INPUTERROR_TAPITacticsTypeType
TAPIERROR_INPUTERROR_TAPIORDERACT = cvar.TAPIERROR_INPUTERROR_TAPIORDERACT
TAPIERROR_INPUTERROR_TAPITriggerConditionType = cvar.TAPIERROR_INPUTERROR_TAPITriggerConditionType
TAPIERROR_INPUTERROR_TAPITriggerPriceTypeType = cvar.TAPIERROR_INPUTERROR_TAPITriggerPriceTypeType
TAPIERROR_INPUTERROR_TAPITradingStateType = cvar.TAPIERROR_INPUTERROR_TAPITradingStateType
TAPIERROR_INPUTERROR_TAPIMarketLevelType = cvar.TAPIERROR_INPUTERROR_TAPIMarketLevelType
TAPIERROR_INPUTERROR_TAPIOrderQryTypeType = cvar.TAPIERROR_INPUTERROR_TAPIOrderQryTypeType
TAPIERROR_DISCONNECT_CLOSE_INIT = cvar.TAPIERROR_DISCONNECT_CLOSE_INIT
TAPIERROR_DISCONNECT_CLOSE_PASS = cvar.TAPIERROR_DISCONNECT_CLOSE_PASS
TAPIERROR_DISCONNECT_READ_ERROR = cvar.TAPIERROR_DISCONNECT_READ_ERROR
TAPIERROR_DISCONNECT_WRITE_ERROR = cvar.TAPIERROR_DISCONNECT_WRITE_ERROR
TAPIERROR_DISCONNECT_BUF_FULL = cvar.TAPIERROR_DISCONNECT_BUF_FULL
TAPIERROR_DISCONNECT_IOCP_ERROR = cvar.TAPIERROR_DISCONNECT_IOCP_ERROR
TAPIERROR_DISCONNECT_PARSE_ERROR = cvar.TAPIERROR_DISCONNECT_PARSE_ERROR
TAPIERROR_DISCONNECT_CONNECT_TIMEOUT = cvar.TAPIERROR_DISCONNECT_CONNECT_TIMEOUT
TAPIERROR_DISCONNECT_INIT_ERROR = cvar.TAPIERROR_DISCONNECT_INIT_ERROR
TAPIERROR_DISCONNECT_HAS_CONNECTED = cvar.TAPIERROR_DISCONNECT_HAS_CONNECTED
TAPIERROR_DISCONNECT_HAS_EXIT = cvar.TAPIERROR_DISCONNECT_HAS_EXIT
TAPIERROR_DISCONNECT_TRY_LATER = cvar.TAPIERROR_DISCONNECT_TRY_LATER
TAPIERROR_DISCONNECT_HEARTBEAT_FAILED = cvar.TAPIERROR_DISCONNECT_HEARTBEAT_FAILED
TAPIERROR_LOGIN = cvar.TAPIERROR_LOGIN
TAPIERROR_LOGIN_USER = cvar.TAPIERROR_LOGIN_USER
TAPIERROR_LOGIN_DDA = cvar.TAPIERROR_LOGIN_DDA
TAPIERROR_LOGIN_LICENSE = cvar.TAPIERROR_LOGIN_LICENSE
TAPIERROR_LOGIN_MODULE = cvar.TAPIERROR_LOGIN_MODULE
TAPIERROR_LOGIN_FORCE = cvar.TAPIERROR_LOGIN_FORCE
TAPIERROR_LOGIN_STATE = cvar.TAPIERROR_LOGIN_STATE
TAPIERROR_LOGIN_PASS = cvar.TAPIERROR_LOGIN_PASS
TAPIERROR_LOGIN_RIGHT = cvar.TAPIERROR_LOGIN_RIGHT
TAPIERROR_LOGIN_COUNT = cvar.TAPIERROR_LOGIN_COUNT
TAPIERROR_LOGIN_NOTIN_SERVERFLAGUSRES = cvar.TAPIERROR_LOGIN_NOTIN_SERVERFLAGUSRES
TAPIERROR_LOGIN_USER_EXPIRED = cvar.TAPIERROR_LOGIN_USER_EXPIRED
TAPIERROR_LOGIN_NO_ACCOUNT = cvar.TAPIERROR_LOGIN_NO_ACCOUNT
TAPIERROR_LOGIN_NO_JGT = cvar.TAPIERROR_LOGIN_NO_JGT
TAPIERROR_LOGIN_ERROR_TIMES = cvar.TAPIERROR_LOGIN_ERROR_TIMES
TAPIERROR_LOGIN_ERROR_AUTHTYPE = cvar.TAPIERROR_LOGIN_ERROR_AUTHTYPE
TAPIERROR_LOGIN_ERROR_AUTHEXPIRED = cvar.TAPIERROR_LOGIN_ERROR_AUTHEXPIRED
TAPIERROR_LOGIN_ERROR_PASSWDEXPIRED = cvar.TAPIERROR_LOGIN_ERROR_PASSWDEXPIRED
TAPIERROR_LOGIN_ERROR_USERTRUST = cvar.TAPIERROR_LOGIN_ERROR_USERTRUST
TAPIERROR_LOGIN_ERROR_CLIENTVERSION = cvar.TAPIERROR_LOGIN_ERROR_CLIENTVERSION
TAPIERROR_LOGIN_ERROR_AUTHCODEINFO = cvar.TAPIERROR_LOGIN_ERROR_AUTHCODEINFO
TAPIERROR_USERINFO_QRY = cvar.TAPIERROR_USERINFO_QRY
TAPIERROR_USERALLRIGHT_QRY = cvar.TAPIERROR_USERALLRIGHT_QRY
TAPIERROR_USERALLACCOUNT_QRY = cvar.TAPIERROR_USERALLACCOUNT_QRY
TAPIERROR_USERPASSWORD_MOD = cvar.TAPIERROR_USERPASSWORD_MOD
TAPIERROR_USERPASSWORD_MOD_SOURCE = cvar.TAPIERROR_USERPASSWORD_MOD_SOURCE
TAPIERROR_USERPASSWORD_MOD_SAME = cvar.TAPIERROR_USERPASSWORD_MOD_SAME
TAPIERROR_USERPASSWORD_MOD_COMPLEXITY = cvar.TAPIERROR_USERPASSWORD_MOD_COMPLEXITY
TAPIERROR_ACCOUNTINFO_QRY = cvar.TAPIERROR_ACCOUNTINFO_QRY
TAPIERROR_TRADENO_QRY = cvar.TAPIERROR_TRADENO_QRY
TAPIERROR_CONTRACTINFO_QRY = cvar.TAPIERROR_CONTRACTINFO_QRY
TAPIERROR_SPECIALOPTIONFUTURE_QRY = cvar.TAPIERROR_SPECIALOPTIONFUTURE_QRY
TAPIERROR_COMMODITYORDERTYPE_QRY = cvar.TAPIERROR_COMMODITYORDERTYPE_QRY
TAPIERROR_ORDERTIMEINFORCE_QRY = cvar.TAPIERROR_ORDERTIMEINFORCE_QRY
TAPIERROR_USER_ORDER_FREQUENCE_QRY = cvar.TAPIERROR_USER_ORDER_FREQUENCE_QRY
TAPIERROR_USERSUBMITAUTHTYPE_ERROR = cvar.TAPIERROR_USERSUBMITAUTHTYPE_ERROR
TAPIERROR_USERSUBMITINFO_EMPTY = cvar.TAPIERROR_USERSUBMITINFO_EMPTY
TAPIERROR_USERAUTHKEYVERSION_ERROR = cvar.TAPIERROR_USERAUTHKEYVERSION_ERROR
TAPIERROR_USERSUBMITINFO_PARTY = cvar.TAPIERROR_USERSUBMITINFO_PARTY
TAPIERROR_USERSUBMITINFO_TESTKEY = cvar.TAPIERROR_USERSUBMITINFO_TESTKEY
TAPIERROR_USERSUBMITINFO_USERNO = cvar.TAPIERROR_USERSUBMITINFO_USERNO
TAPIERROR_ORDERINSERT_ACCOUNT = cvar.TAPIERROR_ORDERINSERT_ACCOUNT
TAPIERROR_ORDERINSERT_ACCOUNT_STATE = cvar.TAPIERROR_ORDERINSERT_ACCOUNT_STATE
TAPIERROR_ORDERINSERT_SIDE_TRADE = cvar.TAPIERROR_ORDERINSERT_SIDE_TRADE
TAPIERROR_ORDERINSERT_OPTIONS_TRADE = cvar.TAPIERROR_ORDERINSERT_OPTIONS_TRADE
TAPIERROR_ORDERINSERT_COMMODITY_TRADE = cvar.TAPIERROR_ORDERINSERT_COMMODITY_TRADE
TAPIERROR_ORDERINSERT_OPEN_RIGHT = cvar.TAPIERROR_ORDERINSERT_OPEN_RIGHT
TAPIERROR_ORDERINSERT_RISK_CHECK = cvar.TAPIERROR_ORDERINSERT_RISK_CHECK
TAPIERROR_ORDERINSERT_CONTRACT = cvar.TAPIERROR_ORDERINSERT_CONTRACT
TAPIERROR_ORDERINSERT_TRADEROUTE = cvar.TAPIERROR_ORDERINSERT_TRADEROUTE
TAPIERROR_ORDERINSERT_POSITIONMAX = cvar.TAPIERROR_ORDERINSERT_POSITIONMAX
TAPIERROR_ORDER_NOTRADE = cvar.TAPIERROR_ORDER_NOTRADE
TAPIERROR_ORDER_CLOSE = cvar.TAPIERROR_ORDER_CLOSE
TAPIERROR_ORDERINSERT_NOTENOUGHFUND = cvar.TAPIERROR_ORDERINSERT_NOTENOUGHFUND
TAPIERROR_ORDERINSERT_ORDERTYPE = cvar.TAPIERROR_ORDERINSERT_ORDERTYPE
TAPIERROR_ORDERINSERT_TIMEINFORCE = cvar.TAPIERROR_ORDERINSERT_TIMEINFORCE
TAPIERROR_ORDERINSERT_NO_TACTICS = cvar.TAPIERROR_ORDERINSERT_NO_TACTICS
TAPIERROR_ORDERINSERT_POSITION_CANNOT_CLOSE = cvar.TAPIERROR_ORDERINSERT_POSITION_CANNOT_CLOSE
TAPIERROR_ORDERINSERT_AUTOCHECK_FAIL = cvar.TAPIERROR_ORDERINSERT_AUTOCHECK_FAIL
TAPIERROR_ORDERINSERT_LME_NOTREADY = cvar.TAPIERROR_ORDERINSERT_LME_NOTREADY
TAPIERROR_ORDERINSERT_CLOSEMODE = cvar.TAPIERROR_ORDERINSERT_CLOSEMODE
TAPIERROR_ORDERINSERT_PARENTNOTENOUGHFUND = cvar.TAPIERROR_ORDERINSERT_PARENTNOTENOUGHFUND
TAPIERROR_SWAP_CONTRACT = cvar.TAPIERROR_SWAP_CONTRACT
TAPIERROR_ORDERINSERT_PRICE = cvar.TAPIERROR_ORDERINSERT_PRICE
TAPIERROR_ORDERINSERT_EFFECT = cvar.TAPIERROR_ORDERINSERT_EFFECT
TAPIERROR_ORDERINSERT_TARGETCONTRACT = cvar.TAPIERROR_ORDERINSERT_TARGETCONTRACT
TAPIERROR_USERNO_NOTHAS_ACCOUNT = cvar.TAPIERROR_USERNO_NOTHAS_ACCOUNT
TAPIERROR_UPPERCHANNEL_BROKEN = cvar.TAPIERROR_UPPERCHANNEL_BROKEN
TAPIERROR_UPPERCHANNEL_NOT_EXIST = cvar.TAPIERROR_UPPERCHANNEL_NOT_EXIST
TAPIERROR_ORDERDELETE_NOT_SYSNO = cvar.TAPIERROR_ORDERDELETE_NOT_SYSNO
TAPIERROR_ORDERDELETE_NOT_STATE = cvar.TAPIERROR_ORDERDELETE_NOT_STATE
TAPIERROR_ORDERACTIVE_NOT_STATE = cvar.TAPIERROR_ORDERACTIVE_NOT_STATE
TAPIERROR_ORDERDELETE_NOT_LAST = cvar.TAPIERROR_ORDERDELETE_NOT_LAST
TAPIERROR_ORDERCHECK_NOT_STATE = cvar.TAPIERROR_ORDERCHECK_NOT_STATE
TAPIERROR_ORDERCHECK_FAIL = cvar.TAPIERROR_ORDERCHECK_FAIL
TAPIERROR_ORDERMODIFY_NOT_STATE = cvar.TAPIERROR_ORDERMODIFY_NOT_STATE
TAPIERROR_ORDERMODIFY_BACK_INPUT = cvar.TAPIERROR_ORDERMODIFY_BACK_INPUT
TAPIERROR_ORDERINSERT_FEE = cvar.TAPIERROR_ORDERINSERT_FEE
TAPIERROR_ORDERINSERT_MARGIN = cvar.TAPIERROR_ORDERINSERT_MARGIN
TAPIERROR_ORDER_NO_PERMIT = cvar.TAPIERROR_ORDER_NO_PERMIT
TAPIERROR_RSPQUOTE_NO_PERMIT = cvar.TAPIERROR_RSPQUOTE_NO_PERMIT
TAPIERROR_RSPQUOTE_CHILD_NO_PERMIT = cvar.TAPIERROR_RSPQUOTE_CHILD_NO_PERMIT
TAPIERROR_TRADENO_NOT_FIND = cvar.TAPIERROR_TRADENO_NOT_FIND
TAPIERROR_ORDER_NO_CLOSE = cvar.TAPIERROR_ORDER_NO_CLOSE
TAPIERROR_QRY_QUOTE_NO_PERMIT = cvar.TAPIERROR_QRY_QUOTE_NO_PERMIT
TAPIERROR_EXPIREDATE_NO_PERMIT = cvar.TAPIERROR_EXPIREDATE_NO_PERMIT
TAPIERROR_CMB_NO_PERMIT = cvar.TAPIERROR_CMB_NO_PERMIT
TAPIERROR_ORDERSERVER_NO_PERMIT = cvar.TAPIERROR_ORDERSERVER_NO_PERMIT
TAPIERROR_POSITION_CANNOT_EXEC_OR_ABANDON = cvar.TAPIERROR_POSITION_CANNOT_EXEC_OR_ABANDON
TAPIERROR_ORDERCHECK_NO_PERMIT = cvar.TAPIERROR_ORDERCHECK_NO_PERMIT
TAPIERROR_ORDERMAXOPENVOL_NO_PERMIT = cvar.TAPIERROR_ORDERMAXOPENVOL_NO_PERMIT
TAPIERROR_ORDERLIMIT_OPEN_NO_PERMIT = cvar.TAPIERROR_ORDERLIMIT_OPEN_NO_PERMIT
TAPIERROR_ORDER_SINGLEVOL_NO_PERMIT = cvar.TAPIERROR_ORDER_SINGLEVOL_NO_PERMIT
TAPIERROR_ORDER_POSITIONVOL_NO_PERMIT = cvar.TAPIERROR_ORDER_POSITIONVOL_NO_PERMIT
TAPIERROR_ORDER_QTY_NO_PERMIT = cvar.TAPIERROR_ORDER_QTY_NO_PERMIT
TAPIERROR_ORDER_APPLY_NO_PERMIT = cvar.TAPIERROR_ORDER_APPLY_NO_PERMIT
TAPIERROR_ORDER_FREQ_OVERRUN = cvar.TAPIERROR_ORDER_FREQ_OVERRUN
TAPIERROR_COMB_NO_SIDEORHEDGE = cvar.TAPIERROR_COMB_NO_SIDEORHEDGE
TAPIERROR_REQQUOTE_EXITREASONABLPRICE = cvar.TAPIERROR_REQQUOTE_EXITREASONABLPRICE
TAPIERROR_RSPQUOTE_PRICE = cvar.TAPIERROR_RSPQUOTE_PRICE
TAPIERROR_RISKORDER_CANCEL = cvar.TAPIERROR_RISKORDER_CANCEL
TAPIERROR_RSPQUOTE_EFFECT = cvar.TAPIERROR_RSPQUOTE_EFFECT
TAPIERROR_ORDERINSERT_SIDEMODE = cvar.TAPIERROR_ORDERINSERT_SIDEMODE
TAPIERROR_AUTOORDER_MAXCOUNT = cvar.TAPIERROR_AUTOORDER_MAXCOUNT
TAPIERROR_SHFEDEEPQUOTE_LIMIT = cvar.TAPIERROR_SHFEDEEPQUOTE_LIMIT
TAPIERROR_SHFEDEEPQUOTE_NODATA = cvar.TAPIERROR_SHFEDEEPQUOTE_NODATA
TAPIERROR_SELFMATCH = cvar.TAPIERROR_SELFMATCH
TAPIERROR_ERRORORDER_MAXCOUNT = cvar.TAPIERROR_ERRORORDER_MAXCOUNT
TAPIERROR_ORDER_UPPERFREQ_OVERRUN = cvar.TAPIERROR_ORDER_UPPERFREQ_OVERRUN
TAPIERROR_ORDER_FREQUENCY = cvar.TAPIERROR_ORDER_FREQUENCY
TAPIERROR_ORDER_QUERYING = cvar.TAPIERROR_ORDER_QUERYING
TAPIERROR_SUBSCRIBEQUOTE_MAX = cvar.TAPIERROR_SUBSCRIBEQUOTE_MAX
TAPIERROR_SUBSCRIBEQUOTE_EXCHANGE_MAX = cvar.TAPIERROR_SUBSCRIBEQUOTE_EXCHANGE_MAX
TAPIERROR_SUBSCRIBEQUOTE_NO_RIGHT = cvar.TAPIERROR_SUBSCRIBEQUOTE_NO_RIGHT
TAPIERROR_SUBSCRIBEQUOTE_NO_EXCHANGE_RIGHT = cvar.TAPIERROR_SUBSCRIBEQUOTE_NO_EXCHANGE_RIGHT
TAPIERROR_SUBSCRIBEQUOTE_COMMODITY_NOT_EXIST = cvar.TAPIERROR_SUBSCRIBEQUOTE_COMMODITY_NOT_EXIST
TAPIERROR_SUBSCRIBEQUOTE_CONTRACT_MAY_NOT_EXIST = cvar.TAPIERROR_SUBSCRIBEQUOTE_CONTRACT_MAY_NOT_EXIST
TAPIERROR_QUOTEFRONT_UNKNOWN_PROTOCOL = cvar.TAPIERROR_QUOTEFRONT_UNKNOWN_PROTOCOL
TAPIERROR_QUOTEFRONT_LOGIN_TOTALCOUNT = cvar.TAPIERROR_QUOTEFRONT_LOGIN_TOTALCOUNT
TAPIERROR_QUOTEFRONT_SUB_COUNT = cvar.TAPIERROR_QUOTEFRONT_SUB_COUNT
TAPIERROR_ORDER_SEND = cvar.TAPIERROR_ORDER_SEND
TAPIERROR_DLG_NULL = cvar.TAPIERROR_DLG_NULL
TAPIERROR_ORDER_FIELD = cvar.TAPIERROR_ORDER_FIELD
TAPIERROR_TRADE_REJ_BYUPPER = cvar.TAPIERROR_TRADE_REJ_BYUPPER
TAPIERROR_ORDER_FORBIDEXEC = cvar.TAPIERROR_ORDER_FORBIDEXEC

class ITapQuoteAPI(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ITapQuoteAPI, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ITapQuoteAPI, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr

    def SetAPINotify(self, apiNotify):
        return _EsunnyApi.ITapQuoteAPI_SetAPINotify(self, apiNotify)

    def SetHostAddress(self, IP, port):
        return _EsunnyApi.ITapQuoteAPI_SetHostAddress(self, IP, port)

    def Login(self, loginAuth):
        return _EsunnyApi.ITapQuoteAPI_Login(self, loginAuth)

    def Disconnect(self):
        return _EsunnyApi.ITapQuoteAPI_Disconnect(self)

    def QryCommodity(self, sessionID):
        return _EsunnyApi.ITapQuoteAPI_QryCommodity(self, sessionID)

    def QryContract(self, sessionID, qryReq):
        return _EsunnyApi.ITapQuoteAPI_QryContract(self, sessionID, qryReq)

    def SubscribeQuote(self, sessionID, contract):
        return _EsunnyApi.ITapQuoteAPI_SubscribeQuote(self, sessionID, contract)

    def UnSubscribeQuote(self, sessionID, contract):
        return _EsunnyApi.ITapQuoteAPI_UnSubscribeQuote(self, sessionID, contract)
    __swig_destroy__ = _EsunnyApi.delete_ITapQuoteAPI
    __del__ = lambda self: None
ITapQuoteAPI_swigregister = _EsunnyApi.ITapQuoteAPI_swigregister
ITapQuoteAPI_swigregister(ITapQuoteAPI)


def CreateTapQuoteAPI(appInfo, iResult):
    return _EsunnyApi.CreateTapQuoteAPI(appInfo, iResult)
CreateTapQuoteAPI = _EsunnyApi.CreateTapQuoteAPI

def FreeTapQuoteAPI(apiObj):
    return _EsunnyApi.FreeTapQuoteAPI(apiObj)
FreeTapQuoteAPI = _EsunnyApi.FreeTapQuoteAPI

def GetTapQuoteAPIVersion():
    return _EsunnyApi.GetTapQuoteAPIVersion()
GetTapQuoteAPIVersion = _EsunnyApi.GetTapQuoteAPIVersion

def SetTapQuoteAPIDataPath(path):
    return _EsunnyApi.SetTapQuoteAPIDataPath(path)
SetTapQuoteAPIDataPath = _EsunnyApi.SetTapQuoteAPIDataPath

def SetTapQuoteAPILogLevel(level):
    return _EsunnyApi.SetTapQuoteAPILogLevel(level)
SetTapQuoteAPILogLevel = _EsunnyApi.SetTapQuoteAPILogLevel
# This file is compatible with both classic and new-style classes.


