rpc_node:
  ip: 127.0.0.1
  port: 9009
rpc:
  dao_web:
    token: 'xxx'
rpc_token:
  dao_web: 'xxx'
  dao_strategy: ''
aes_root_key: ''
sms:
  sdkappid: ''
  appkey: ''
mongo:
  'dao_trade':
    mode: ReplicaSet
    connstr: 'mongodb://{}:{}@127.0.0.1:37011,127.0.0.1:37012,127.0.0.1:37013/{}'
    repl_name: ''
    db_name: ''
    db_user: ''
    db_pwd: ''
  'test':
    mode: ''
    connstr: '127.0.0.1:27017'
    db_name: ''
    db_user: ''
    db_pwd: ''
ctp_rpc:
  host: 127.0.0.1
  port: 10003
ctp_ex_dict:
  SHFE: ['rb', 'fu', 'hc', 'sp']
  DCE: ['a', 'b', 'm', 'y', 'c', 'p', 'j', 'jm', 'l', 'v', 'pp', 'jd', 'cs', 'i', 'eg', 'rr', 'eb']
  CZCE: ['CF', 'CY', 'SR', 'TA', 'OI', 'MA', 'FG', 'RM', 'ZC', 'SF', 'SM', 'AP', 'CJ', 'UR', 'SA']
  CFFEX: ['IF', 'IC', 'IH']
  INE: ['sc']
close_tyday_ex_list: ['SHFE', 'INE']
tick_size_dict:
  {
    'rb': 1, 'fu': 1, 'hc': 1, 'sp': 1,

    'a': 1, 'b': 1, 'm': 1, 'y': 2, 'c': 1, 'p': 2,
    'j': 0.5, 'jm': 0.5, 'l': 5, 'v': 5, 'pp': 1, 'jd': 1,
    'cs': 1, 'i': 0.5, 'eg': 1, 'rr': 1, 'eb': 1,

    'CF': 5, 'CY': 5, 'SR': 1, 'TA': 2, 'OI': 2,
    'MA': 1, 'FG': 1, 'RM': 1, 'ZC': 0.2, 'SF': 2,
    'SM': 2, 'AP': 1, 'CJ': 5, 'UR': 1, 'SA': 1,

    'IF': 0.2, 'IC': 0.2, 'IH': 0.2,

    'sc': 0.1
  }
